# Generated by Django 4.2.11 on 2024-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(default='exit', max_length=250),
            preserve_default=False,
        ),
    ]
