# Generated by Django 4.2.11 on 2024-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appcollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('subcategory', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('points', models.IntegerField()),
            ],
        ),
    ]
